# Generated by Django 5.1 on 2024-11-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('nota3', models.FloatField()),
                ('fecha_ingreso', models.DateField()),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
    ]
